# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

before_install:
  - sudo tlmgr update --self
  - sudo tlmgr install framed

os:
- linux
- osx

r:
 - release
 - 3.4

r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'
