# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

before_install:
  - sudo apt-get install pandoc
  - Rscript -e 'install.packages("Rdpack")'
  - Rscript -e 'install.packages("tinytex")'
  - Rscript -e 'install.packages("pander")'
  - Rscript -e 'tinytex::install_tinytex(force=TRUE)'
  - sudo apt-get install ghostscript

env:
  - NOT_CRAN=true

os:
- linux

r:
 - release
 - devel
     env:
       - R_KEEP_PKG_SOURCE=yes
       - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
       - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
       - _R_CHECK_CONNECTIONS_LEFT_OPEN_=true
       - _R_CHECK_LENGTH_1_CONDITION_=true
       - _R_CHECK_LENGTH_1_LOGIC2_=true
       - _R_CLASS_MATRIX_ARRAY_=true

r_packages:
  - covr
  - tinytex
  - pander

after_success:
- travis_wait 45 Rscript -e 'covr::codecov(quiet = FALSE, type = "tests")'
