# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

before_install:
  - sudo apt-get install pandoc
  - sudo apt-get install textlive
  - Rscript -e 'install.packages("tinytex")'
  - Rscript -e 'install.packages("pander")'
  - Rscript -e 'tinytex::install_tinytex(force=TRUE)'
  - sudo apt-get install ghostscript

os:
- linux

r:
 - release
 - devel

r_packages:
  - covr
  - tinytex
  - pander

after_success:
- Rscript -e 'covr::codecov()'
