# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

before_install:
  - Rscript -e 'install.packages("tinytex")'
  - Rscript -e 'tinytex::install_tinytex(force=TRUE)'

os:
- linux
- osx

r:
 - release
 - devel

r_packages:
  - covr
  - tinytex

after_success:
- Rscript -e 'covr::codecov()'
