# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
before_install:
  - sudo apt-get install pandoc
  - Rscript -e 'install.packages("Rdpack")'
  - Rscript -e 'install.packages("tinytex")'
  - Rscript -e 'install.packages("pander")'
  - Rscript -e 'tinytex::install_tinytex(force=TRUE)'
  - sudo apt-get install ghostscript

env:
  - _R_CLASS_MATRIX_ARRAY_=true
  - _R_CHECK_LENGTH_1_CONDITION_="package:_R_CHECK_PACKAGE_NAME_,verbose"
os:
- linux

r:
 - release
 - devel

r_packages:
  - covr
  - tinytex
  - pander

after_success:
- travis_wait 45 Rscript -e 'covr::codecov(quiet = FALSE, type = "tests")'
